name: firebase_messaging_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
